// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/iskorotkov/igaming-balance-backend/internal/domain"
	"github.com/shopspring/decimal"
)

type TxSource string

const (
	TxSourceGame    TxSource = "Game"
	TxSourcePayment TxSource = "Payment"
	TxSourceService TxSource = "Service"
)

func (e *TxSource) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TxSource(s)
	case string:
		*e = TxSource(s)
	default:
		return fmt.Errorf("unsupported scan type for TxSource: %T", src)
	}
	return nil
}

type NullTxSource struct {
	TxSource TxSource
	Valid    bool // Valid is true if TxSource is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTxSource) Scan(value interface{}) error {
	if value == nil {
		ns.TxSource, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TxSource.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTxSource) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TxSource), nil
}

type TxState string

const (
	TxStateDeposit  TxState = "Deposit"
	TxStateWithdraw TxState = "Withdraw"
)

func (e *TxState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TxState(s)
	case string:
		*e = TxState(s)
	default:
		return fmt.Errorf("unsupported scan type for TxState: %T", src)
	}
	return nil
}

type NullTxState struct {
	TxState TxState
	Valid   bool // Valid is true if TxState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTxState) Scan(value interface{}) error {
	if value == nil {
		ns.TxState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TxState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTxState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TxState), nil
}

type Balance struct {
	BalanceID uuid.UUID
	Amount    decimal.Decimal
}

type Tx struct {
	CreatedAt time.Time
	DeletedAt *time.Time
	TxID      uuid.UUID
	BalanceID uuid.UUID
	Source    domain.Source
	State     domain.State
	Amount    decimal.Decimal
}
